### PR TITLE
bug fixes

### PR DESCRIPTION
**Pull request by tlylt**
- comment out console log
- fix an image size warning
- update background music
- adjust sound volume again as the volume is really loud, I think even 0.1 is still ok for reward sound
- fix cursor for character selection
- add in a temporary toast for mobile viewing to prompt user to rotate:
image

### CODE REVIEW

**Review by shiweing — COMMENTED** [review]
Not sure if you updated the bgm to the new one, the old one is still playing for me?

**Comment by tlylt** [comment]
> Not sure if you updated the bgm to the new one, the old one is still playing for me?

looks like i missed out one place, should work now

**Comment by shiweing** [comment]
> > Not sure if you updated the bgm to the new one, the old one is still playing for me?
> 
> looks like i missed out one place, should work now

It's playing! Maybe it could be louder since the new music is slower

**Comment by tlylt** [comment]
> > > Not sure if you updated the bgm to the new one, the old one is still playing for me?
> > 
> > 
> > looks like i missed out one place, should work now
> 
> It's playing! Maybe it could be louder since the new music is slower

maybe we try with this volume first? I think sometimes background music can affect reading, and hence a softer one might be more unintrusive

**Review by shiweing — APPROVED** [review]
LGTM!

**Comment by shiweing** [comment]
> > > > Not sure if you updated the bgm to the new one, the old one is still playing for me?
> > > 
> > > 
> > > looks like i missed out one place, should work now
> > 
> > 
> > It's playing! Maybe it could be louder since the new music is slower
> 
> maybe we try with this volume first? I think sometimes background music can affect reading, and hence a softer one might be more unintrusive

I see, sure

**Pull request merged**
